Added prost::Message support
ivmarkov/channel-bridge pull request #1
Opened 2022-10-13 11:36 UTC by Volkalex28

I added support for prost::Message. Think it is good feature for this crate :)

2022-10-13 12:14 UTC, ivmarkov commented
Thank you for contributing. :)

Can you run `cargo fmt` and then push? Then I'll comment on the PR shortly.

2022-10-14 18:42 UTC, Volkalex28 commented
Do I need to fix the merge conflict?

2022-10-15 05:26 UTC, ivmarkov commented
I would appreciate that, yes.

2022-10-21 05:45 UTC, ivmarkov requested changes

2022-10-21 05:45 UTC, ivmarkov commented on Cargo.toml
> +embedded-svc-prost = ["nightly", "dep:embedded-svc", "embassy-futures", "log", "prost", "heapless", "postcard"]
The support for `prost` should be implemented for `embedded-svc` (as you did) *but also* for the `edge-net` feature as well.  It is just swapping out the `postcard` serde in the `ws` module with `prost`.

Therefore, best is to just have a `prost` feature, which in fact you can implicitly do by marking the `prost` dependency as optional.

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/pubsub.rs
> +#[cfg(any(feature = "embedded-svc", feature = "embedded-svc-prost"))]
Revert to the original code.

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/pubsub.rs
> +#[cfg(any(feature = "embedded-svc", feature = "embedded-svc-prost"))]
Ditto: revert to the original code.

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/ws.rs
> +#[cfg(any(
Ditto: revert to the original code.

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/ws.rs
> +#[cfg(any(feature = "embedded-svc", feature = "embedded-svc-prost"))]
Ditto.

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/ws.rs
> +#[cfg(any(
Ditto.

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/ws.rs
> +    #[cfg(feature = "embedded-svc-prost")]
Now here and further down on all `ProstError` code blocks you should conditionalize by `#[cfg(feature = "prost")]` instead.

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/ws.rs
> +                #[cfg(any(feature = "edge-net", feature = "embedded-svc"))]
`#[cfg(not(feature = "prost"))]`

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/ws.rs
> +                #[cfg(feature = "embedded-svc-prost")]
`#[cfg(feature = "prost")]`

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/ws.rs
> +    #[cfg(any(feature = "edge-net", feature = "embedded-svc"))]
`#[cfg(not(feature = "prost"))]`

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/ws.rs
> +
`#[cfg(feature = "prost")]`

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/ws.rs
> +    #[cfg(feature = "embedded-svc-prost")]
Dito.

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/ws.rs
> +#[cfg(any(feature = "embedded-svc", feature = "embedded-svc-prost"))]
Revert. Also and again: pleae note that ideally you should conditionalize the `edge-net` WS sender/receiver impls with `prost`, not just the `embedded-svc` ones.

2022-10-21 05:45 UTC, ivmarkov commented on src/asynch/ws.rs
> +    #[cfg(feature = "embedded-svc-prost")]
Ditto and so on for `embedded-svc-prost`.

2022-10-27 17:28 UTC, ivmarkov commented
Changes seem fine!
One final req: can you fix the latest clippy errors (I know these are in the postcard code, not prost so I might be asking too much) but if you have the project checked out and handy...

Then I'll merge.

2022-10-27 17:33 UTC, Volkalex28 commented
> cargo clippy - done

2022-10-27 17:54 UTC, ivmarkov commented
Thanks!

2022-10-27 17:54 UTC, merged